module.exports = {
  someSidebar: {
    // Docusaurus: ['doc1', 'doc2', 'doc3'],
    // Features: ['mdx'],
    Notes: ["0-notes/1-reading-guide", "0-notes/2-basic-github"],
    Basics: [
      "1-basics/1-install",
      "1-basics/2-folder-structure",
      "1-basics/3-create-pages",
      "1-basics/4-link-component",
      "1-basics/5-navbar",
      "1-basics/6-layout-component",
    ],
    CSS: [
      "2-css/1-css-intro",
      "2-css/2-inline-css",
      "2-css/3-global-css",
      "2-css/4-naming-issue",
      "2-css/5-css-modules",
      "2-css/6-styled-components",
    ],
    GraphQL: [
      "3-graphql/1-gatsby-and-graphql-intro",
      "3-graphql/2-gatsby-datalayer",
      "3-graphql/3-graphiql-interface",
      "3-graphql/4-sitemetadata",
      "3-graphql/5-first-query",
      "3-graphql/6-explorer-example",
      "3-graphql/7-render-intro",
      "3-graphql/8-example-setup",
      "3-graphql/9-code-explorer-usestaticquery",
      "3-graphql/10-usestaticquery-and-graphql",
      "3-graphql/11-field-alias",
      "3-graphql/12-query-keyword-and-name",
      "3-graphql/13-staticquery-component",
      "3-graphql/14-pagequery",
    ],
    Images: [
      "4-images/1-images-setup",
      "4-images/2-gatsby-source-filesystem-plugin-install",
      "4-images/3-allfile-field",
      "4-images/4-query-arguments",
      "4-images/5-file-field",
      "4-images/6-sourceinstancename",
      "4-images/7-install-gatsby-image",
      "4-images/8-gatsby-image-overview",
      "4-images/9-gatsby-image-query",
      "4-images/10-render-gatsby-image-setup",
      "4-images/11-render-gatsby-image",
      "4-images/12-gatsby-image-optimizations",
      "4-images/13-maxwidth-parameter",
    ],
    Data: [
      "5-data/1-data-intro",
      "5-data/2-local-data-vs-external-data",
      "5-data/3-headless-cms-intro",
      "5-data/4-contentful-info",
      "5-data/5-contentful-interface",
      "5-data/6-content-type",
      "5-data/7-content",
      "5-data/8-connect-to-contentful",
      "5-data/9-products-query",
      "5-data/10-products-page",
      "5-data/11-products-page-css",
      "5-data/12-nested-pages",
      "5-data/13-product-template",
      "5-data/14-slug-query",
      "5-data/15-gatsby-node",
      "5-data/16-slug-info",
      "5-data/17-single-product-query",
      "5-data/18-query-variables",
      "5-data/19-product-template-complete",
      "5-data/20-product-template-css",
      "5-data/21-docs",
    ],
    Deploy: [
      "6-deploy/1-env-variables",
      "6-deploy/2-gatsby-build",
      "6-deploy/3-drag-and-drop",
      "6-deploy/4-continuous-deployment",
      "6-deploy/5-webhooks",
      "6-deploy/6-source-code",
    ],
    "Project - Portfolio": ["7-project-portfolio/Test"],
    "Project - MDX Blog": ["8-project-mdx-blog/Test"],
    "Project - Airtable": ["9-project-airtable/Test"],
  },
}
